//
//  SXRSDKProtocolDefine_CZJK.h
//  SXRSDK
//
//  Created by qf on 16/9/23.
//  Copyright © 2016年 Keeprapid. All rights reserved.
//

#ifndef SXRSDKProtocolDefine_CZJK_h
#define SXRSDKProtocolDefine_CZJK_h


#endif /* SXRSDKProtocolDefine_CZJK_h */

#import "SXRSDKCommonDef.h"

//子状态

#define SUB_STATE_CZJK_WAIT_GETMAC_RSP                  SUB_STATE_BEGIN_CZJK+1
#define SUB_STATE_CZJK_WAIT_GETFW_RSP                   SUB_STATE_BEGIN_CZJK+2
#define SUB_STATE_CZJK_WAIT_READTIME_RSP                SUB_STATE_BEGIN_CZJK+3
#define SUB_STATE_CZJK_WAIT_SETTIME_RSP                 SUB_STATE_BEGIN_CZJK+4
#define SUB_STATE_CZJK_WAIT_GETCURRENTDATA_RSP          SUB_STATE_BEGIN_CZJK+5
#define SUB_STATE_CZJK_WAIT_GETHISTORYDATA_RSP          SUB_STATE_BEGIN_CZJK+6
#define SUB_STATE_CZJK_WAIT_SETPERSONINFO_RSP           SUB_STATE_BEGIN_CZJK+7
#define SUB_STATE_CZJK_WAIT_SETSLEEPTIME_RSP            SUB_STATE_BEGIN_CZJK+8
#define SUB_STATE_CZJK_WAIT_SETPARAM_RSP                SUB_STATE_BEGIN_CZJK+9
#define SUB_STATE_CZJK_WAIT_CLEAR_RSP                   SUB_STATE_BEGIN_CZJK+10
#define SUB_STATE_CZJK_WAIT_SETWEATHER_RSP              SUB_STATE_BEGIN_CZJK+11
#define SUB_STATE_CZJK_WAIT_ANTILOST_RSP                SUB_STATE_BEGIN_CZJK+12
#define SUB_STATE_CZJK_WAIT_ANCSPAIR_RSP                SUB_STATE_BEGIN_CZJK+13
#define SUB_STATE_CZJK_WAIT_SENSOR_CHANGE_RSP           SUB_STATE_BEGIN_CZJK+14
#define SUB_STATE_CZJK_WAIT_NODIC_INTO_OTA_RSP          SUB_STATE_BEGIN_CZJK+15
#define SUB_STATE_CZJK_WAIT_SETHYDRATION_RSP            SUB_STATE_BEGIN_CZJK+16
#define SUB_STATE_CZJK_WAIT_GETSPORTDATA_RSP            SUB_STATE_BEGIN_CZJK+17
#define SUB_STATE_CZJK_WAIT_SETSEDETARYALARM_RSP        SUB_STATE_BEGIN_CZJK+18
#define SUB_STATE_CZJK_WAIT_SETNOTIFICATION_RSP         SUB_STATE_BEGIN_CZJK+19
#define SUB_STATE_CZJK_WAIT_SETALARMNAME                SUB_STATE_BEGIN_CZJK+20

//命令
#define CMD_CZJK_GETMAC @"CZJKGetMacid"
#define CMD_CZJK_GETFW @"CZJKGetFirmware"
#define CMD_CZJK_GETHISTORYDATA @"CZJKGetHistoryData"
#define CMD_CZJK_GETSPORTDATA @"CZJKGetSportData"
#define CMD_CZJK_GETCURRENTDATA @"CZJKGetCurrentData"
#define CMD_CZJK_CLEAR @"CZJKClear"
#define CMD_CZJK_READTIME @"CZJKReadTime"
#define CMD_CZJK_SETTIME @"CZJKSetTime"
#define CMD_CZJK_ANTILOST @"CZJKAntilost"
#define CMD_CZJK_WEATHER @"CZJKSendWeather"
#define CMD_CZJK_SETPERSON @"CZJKSetPersonInfo"
#define CMD_CZJK_SETHYDRATIONALARM @"CZJKSetHydrationAlarm"
//暂时无效
#define CMD_CZJK_SETSLEEPTIME @"CZJKSetSleepTime"
#define CMD_CZJK_SETDEVICEPARAM @"CZJKSetDeviceParam"
#define CMD_CZJK_ANCSPAIR @"CZJKSendANCSPair"
#define CMD_CZJK_SENSOR_CHANGE @"CZJKSetSensorState"
#define CMD_CZJK_NORDIC_INTO_OTA @"CZJKSendNodicOtaStart"
#define CMD_CZJK_SETSEDENTARYALARM @"CZJKSetSedentaryAlarm"
#define CMD_CZJK_SETNOTIFICATION @"CZJKSetNotification"
#define CMD_CZJK_SETALARMNAME @"CZJKSetAlarmName"

//协议定义
#define CZJK_DATA_TIME_INTERVAL  60*10
#define CZJK_MAX_STORE_DATA_TIME  6*24*60*60
#define CZJK_MAX_STORE_SPORT_DATA_TIME 2*24*60*60

//phone 2 device
#define CZJK_PHONE2DEVICE_SET_PERSONINFO 0x83
#define CZJK_PHONE2DEVICE_SET_HYDRATION 0x84
#define CZJK_PHONE2DEVICE_READ_HISTORY_DATA 0xC4
#define CZJK_PHONE2DEVICE_READ_SPORT_DATA 0xA2
#define CZJK_PHONE2DEVICE_READ_CURRENT_DATA 0xC6
#define CZJK_PHONE2DEVICE_CLEAR_DATA 0x88
#define CZJK_PHONE2DEVICE_SET_DEVICE_TIME 0xC2
#define CZJK_PHONE2DEVICE_READ_DEVICE_TIME 0x89
#define CZJK_PHONE2DEVICE_SET_SLEEP_TIME 0x9D
#define CZJK_PHONE2DEVICE_SET_PARAM 0x9B
#define CZJK_PHONE2DEVICE_SET_SEDENTARY 0x86

#define CZJK_PHONE2DEVICE_WEATHER 0xF2
#define CZJK_PHONE2DEVICE_ANTILOST 0xF3
#define CZJK_PHONE2DEVICE_GETMAC 0xFA
#define CZJK_PHONE2DEVICE_GETFIREMWARE 0xFB
#define CZJK_PHONE2DEVICE_NOTIFY 0xFF

#define CZJK_PHONE2DEVICE_SENSOR_CHANGE 0x93

#define CZJK_PHONE2DEVICE_ANCS_PAIR 0xA1
#define CZJK_PHONE2DEVICE_NORDIC_INTO_OTA 0xFC
#define CZJK_PHONE2DEVICE_NORDIC_INTO_OTA2 0x24
#define CZJK_PHONE2DEVICE_SETALARMNAME 0xFD

//bong 2 phone
#define CZJK_DEVICE2PHONE_SET_PERSONINFO_OK 0x23
#define CZJK_DEVICE2PHONE_SET_HYDRATION_OK 0x39
#define CZJK_DEVICE2PHONE_READ_HISTORY_DATA_OK 0x24
#define CZJK_DEVICE2PHONE_READ_DATA_CURVE_BY_DATE_OK 0x31
#define CZJK_DEVICE2PHONE_READ_CURRENT_DATA_OK 0x26
#define CZJK_DEVICE2PHONE_CLEAR_DATA_OK 0x28
#define CZJK_DEVICE2PHONE_SET_DEVICE_TIME_OK 0x22
#define CZJK_DEVICE2PHONE_READ_DEVICE_TIME_OK 0x29
#define CZJK_DEVICE2PHONE_SEDENTARY_OK 0x32

#define CZJK_DEVICE2PHONE_SET_PERSONINFO_ERR 0x03
#define CZJK_DEVICE2PHONE_READ_HISTORY_DATA_ERR 0x04
#define CZJK_DEVICE2PHONE_READ_CURRENT_DATA_ERR 0x06
#define CZJK_DEVICE2PHONE_CLEAR_DATA_ERR 0x08
#define CZJK_DEVICE2PHONE_SET_DEVICE_TIME_ERR 0x02
#define CZJK_DEVICE2PHONE_READ_DEVICE_TIME_ERR 0x09
#define CZJK_DEVICE2PHONE_SEDENTARY_ERR 0x0D

#define CZJK_DEVICE2PHONE_ANTILOST 0xF3
#define CZJK_DEVICE2PHONE_REQUEST_TIME 0xF4
#define CZJK_DEVICE2PHONE_PHOTO 0xF5
#define CZJK_DEVICE2PHONE_MUSIC 0xF6
#define CZJK_DEVICE2PHONE_GETMAC 0xFA
#define CZJK_DEVICE2PHONE_GETFIRMWARE 0xFB

#define CZJK_DEVICE2PHONE_SET_SLEEP_TIME_OK 0x2D
#define CZJK_DEVICE2PHONE_SET_SLEEP_TIME_ERR 0x1D

#define CZJK_DEVICE2PHONE_SET_BANDPRAM_OK 0x2B
#define CZJK_DEVICE2PHONE_SET_BANDPRAM_ERR 0x1B

#define CZJK_DEVICE2PHONE_READ_SPORT_DATA 0xA2

#define CZJK_DEVICE2PHONE_ANCS_OK 0xA1
#define CZJK_DEVICE2PHONE_SENSOR_CHANGE_OK 0x33
#define CZJK_DEVICE2PHONE_SENSOR_CHANGE_ERR 0x13

#define CZJK_DEVICE2PHONE_SENSOR_REPORT 0x99

#define CZJK_DEVICE2PHONE_SETALARMNAME_OK 0xFD
#define CZJK_DEVICE2PHONE_SETALARMNAME_ERR 0x3D


////参数定义
#define CZJK_PARAM_LID_MONDAY 0x01
#define CZJK_PARAM_LID_TUESDAY 0x02
#define CZJK_PARAM_LID_WEDNESDAY 0x03
#define CZJK_PARAM_LID_THURSDAY 0x04
#define CZJK_PARAM_LID_FRIDAY 0x05
#define CZJK_PARAM_LID_SATURDAY 0x06
#define CZJK_PARAM_LID_SUNDAY 0x07
#define CZJK_PARAM_LID_CURRENT_STEPS 0x08

#define CZJK_PARAM_ANTILOST_TYPE @"antilosttype"
#define CZJK_PARAM_ALARM_ENABLE @"alarmenable"
#define CZJK_PARAM_HOUR @"hour"
#define CZJK_PARAM_MINUTE @"minute"
#define CZJK_PARAM_START_HOUR @"starthour"
#define CZJK_PARAM_START_MINUTE @"startminute"
#define CZJK_PARAM_END_HOUR @"endhour"
#define CZJK_PARAM_END_MINUTE @"endminute"
#define CZJK_PARAM_REPEAT_HOUR @"repeathour"
#define CZJK_PARAM_REPEAT_TIMES @"repeattimes"
#define CZJK_PARAM_SNOOZE @"repeattimes"
#define CZJK_PARAM_WEEKLY @"weekly"
#define CZJK_PARAM_ALARMLIST @"alarmlist"
#define CZJK_PARAM_HEIGHT @"height"
#define CZJK_PARAM_WEIGHT @"weight"
#define CZJK_PARAM_STRIDE @"stride"
#define CZJK_PARAM_UNIT @"unit"
#define CZJK_PARAM_GENDER @"gender"
#define CZJK_PARAM_SLEEPSTARTHOUR @"slpstarthr"
#define CZJK_PARAM_SLEEPSTARTMINUTE @"slpstartmin"
#define CZJK_PARAM_SLEEPENDHOUR @"slpendhr"
#define CZJK_PARAM_SLEEPENDMINUTE @"slpendmin"
#define CZJK_PARAM_SLEEPENDMINUTE @"slpendmin"
#define CZJK_PARAM_TARGETSTEP @"targetstep"
#define CZJK_PARAM_PROTCOLVERSION @"protocolversion"
#define CZJK_PARAM_YEAR @"year"
#define CZJK_PARAM_MONTH @"month"
#define CZJK_PARAM_DAY @"day"
#define CZJK_PARAM_SENSOR_MODE @"CZJKSensorMode"
#define CZJK_PARAM_SENSOR_ONOFF @"CZJKSensorONOFF"
#define CZJK_PARAM_SENSOR_REPORT @"CZJKSensorReport"
#define CZJK_PARAM_PROTOCOL_VERSION @"CZJKProtocolVersion"
#define CZJK_PARAM_ALARM_ID @"CZJKAlarmID"
#define CZJK_PARAM_ALARM_NAME @"CZJKAlarmName"
#define CZJK_PARAM_SLEEP1_ENABLE @"CZJKSLPENABLE1"
#define CZJK_PARAM_SLEEP1_START_H @"CZJKSLPSTARTH1"
#define CZJK_PARAM_SLEEP1_START_M @"CZJKSLPSTARTM1"
#define CZJK_PARAM_SLEEP1_END_H @"CZJKSLPENDH1"
#define CZJK_PARAM_SLEEP1_END_M @"CZJKSLPENDM1"
#define CZJK_PARAM_SLEEP2_ENABLE @"CZJKSLPENABLE2"
#define CZJK_PARAM_SLEEP2_START_H @"CZJKSLPSTARTH2"
#define CZJK_PARAM_SLEEP2_START_M @"CZJKSLPSTARTM2"
#define CZJK_PARAM_SLEEP2_END_H @"CZJKSLPENDH2"
#define CZJK_PARAM_SLEEP2_END_M @"CZJKSLPENDM2"
#define CZJK_PARAM_SLEEP3_ENABLE @"CZJKSLPENABLE3"
#define CZJK_PARAM_SLEEP3_START_H @"CZJKSLPSTARTH3"
#define CZJK_PARAM_SLEEP3_START_M @"CZJKSLPSTARTM3"
#define CZJK_PARAM_SLEEP3_END_H @"CZJKSLPENDH3"
#define CZJK_PARAM_SLEEP3_END_M @"CZJKSLPENDM3"
#define CZJK_PARAM_SCREEN_TIME @"CZJKScreenTime"
#define CZJK_PARAM_LOWBATTERYALARM @"CZJKLowatteralarm"
#define CZJK_PARAM_ENABLE_INCOMINGCALL @"CZJK_INCOMINGCALL"
#define CZJK_PARAM_ENABLE_SMS @"CZJK_SMS"
#define CZJK_PARAM_ENABLE_QQ @"CZJK_QQ"
#define CZJK_PARAM_ENABLE_WECHAT @"CZJK_WECHAT"

#define CZJK_PARAM_VALUE_FIND_DEVICE_START 0x01
#define CZJK_PARAM_VALUE_FIND_DEVICE_STOP 0xA1

//协议类型定义
#define CZJK_PROTOCOL_VERSION_GOBAND @"goband"
#define CZJK_PROTOCOL_VERSION_FITRIST @"fitrist"
#define CZJK_PROTOCOL_VERSION_PUZZLE @"puzzle"

//参数定义 for 闹钟
#define CZJK_ALARM_PERIOD_1 0x01
#define CZJK_ALARM_PERIOD_2 0x02
#define CZJK_ALARM_PERIOD_3 0x04
#define CZJK_ALARM_PERIOD_4 0x08
#define CZJK_ALARM_PERIOD_5 0x10
#define CZJK_ALARM_PERIOD_6 0x20
#define CZJK_ALARM_PERIOD_7 0x40

#define CZJK_ALARM_WORKDAY 0x1F
#define CZJK_ALARM_ALLDAY 0x7F
//常亮定义
#define DEF_ENABLE @"1"
#define DEF_DISABLE @"0"

//设备参数

#define BONGINFO_KEY_CZJK_ENABLE_INCOMINGCALL @"CZJK_INCOMINGCALL"
#define BONGINFO_KEY_CZJK_ENABLE_SMS @"CZJK_SMS"
#define BONGINFO_KEY_CZJK_ENABLE_QQ @"CZJK_QQ"
#define BONGINFO_KEY_CZJK_ENABLE_WECHAT @"CZJK_WECHAT"
#define BONGINFO_KEY_SLEEPSTARTTIME @"SLEEPSTART"
#define BONGINFO_KEY_SLEEPENDTIME @"SLEEPEND"
#define BONGINFO_KEY_LAST4NAME @"LSTNAME"
#define BONGINFO_KEY_CZJK_LOWBATTERYALARM @"CZJK_LOWBATT"

//通知消息
#define notify_key_CZJK_read_history_data_finish @"CZJKreadhistoryfinish"
#define notify_key_CZJK_read_sport_data_finish @"CZJKreadsportfinish"
#define notify_key_CZJK_did_read_current_data @"CZJKreadcurrentdata"
#define notify_key_CZJK_did_read_history_data @"CZJKreadhistorydata"
#define notify_key_CZJK_did_read_sensor_report @"CZJKSensorReport"
#define notify_key_CZJK_did_sensor_state_change @"CZJKSensorChange"
#define notify_key_CZJK_did_read_sport_data @"CZJKreadsportdata"

//消息通知参数
#define CZJK_NOTIFY_PARAM_CURRENT_STEPS @"CZJKSteps"
#define CZJK_NOTIFY_PARAM_CURRENT_CAL @"CZJKCal"
#define CZJK_NOTIFY_PARAM_CURRENT_DIST @"CZJKDist"
#define CZJK_NOTIFY_PARAM_SENSORTYPE @"CZJKSensorType"
#define CZJK_NOTIFY_PARAM_SENSORVALUE @"CZJKSensorValue"
#define CZJK_NOTIFY_PARAM_SENSORSTATE @"CZJKSensorState"
#define CZJK_NOTIFY_PARAM_YEAR @"CZJKYear"
#define CZJK_NOTIFY_PARAM_MONTH @"CZJKMonth"
#define CZJK_NOTIFY_PARAM_DAY @"CZJKDay"
#define CZJK_NOTIFY_PARAM_HOUR @"CZJKHour"
#define CZJK_NOTIFY_PARAM_MINUTE @"CZJKMinute"
#define CZJK_NOTIFY_PARAM_SECOND @"CZJKSecond"
#define CZJK_NOTIFY_PARAM_WEEKDAY @"CZJKWeekday"
#define CZJK_NOTIFY_PARAM_HISTORY_DATATYPE @"CZJKHistoryDatatype"
#define CZJK_NOTIFY_PARAM_SPORTMODE @"CZJKSportMode"
#define CZJK_NOTIFY_PARAM_SPORTSTEP @"CZJKSportStep"
#define CZJK_NOTIFY_PARAM_SPORTDURATION @"CZJKSportDuration"
#define CZJK_NOTIFY_PARAM_SPORTCAL @"CZJKSportCal"
#define CZJK_NOTIFY_PARAM_STEP @"CZJKStep"
#define CZJK_NOTIFY_PARAM_CAL @"CZJKCal"
#define CZJK_NOTIFY_PARAM_DISTANCE @"CZJKDist"



//消息通知参数值
#define CZJK_NOTIFY_VALUE_SENSORON 1
#define CZJK_NOTIFY_VALUE_SENSOROFF 0


